# Generated by Django 4.2 on 2023-04-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    # 테이블이 생성되어졌다.
    # models에서 논리적 생성작업 후 여기서 물리적 작업을 진행한다.
    # Migration 작업 후 Migrate 작업 진행한다. 둘이 같이 간다고 생각하면됨.

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
                ("pub_date", models.DateTimeField()),
            ],
        ),
    ]
